### ISSUE TITLE
[CY-2431] ts-lint support for codelyzer rules

### ISSUE THREAD

**Issue by siddharth1903** [codacy/codacy-tslint#12]
Hi,

We're looking to additionally implement, on top of tslint, a few codelyzer rules related to accessibility of sites. Codelyzer is  widely used amongst the angular community for static code analysis.
https://github.com/mgechev/codelyzer/

Can you guys please let me know how do i enable rules codelyzer exposes on top of tslint?

Specific rules i'm looking for
  "template-accessibility-alt-text": true,
    "template-accessibility-elements-content": true,
    "template-accessibility-label-for": true,
    "template-accessibility-tabindex-no-positive": true,
    "template-accessibility-table-scope": true,
    "template-accessibility-valid-aria": true,
    "template-click-events-have-key-events": true,
    "template-mouse-events-have-key-events": true,
    "template-no-autofocus": true,
    "template-no-distracting-elements": true

**Comment by franciscodua** [comment]
Hi @siddharth1903 
In our TSLint tool, we have the [tslint-angular](https://www.npmjs.com/package/tslint-angular) plugin installed. According to their documentation, they include codelyzer rules in the plugin.

Although we don't expose the codelyzer rules in the UI configuration, you can use a `tslint.json` configuration file in your repository to configure it.

Is this enough for your use case? Let us know if this doesn't work for you.

**Comment by siddharth1903** [comment]
@franciscodua yes that should suffice... can you give me a short example of how we can use them with codacy? We have had builds failing evaluation of these rules, since we have configured the extends parameter in tsconfig that could not  work in codacy since node_modules would never be commited along with our commits

**Comment by franciscodua** [comment]
Hey @siddharth1903 
Try adding a `tslint.json` to your root folder with the configurations you need/want. For angular, you can try something like what the documentation for this plugin describes https://www.npmjs.com/package/tslint-angular#how-to-use

**Comment by franciscodua** [comment]
I'm closing this issue, but if the suggestion didn't work out for you let us know by re-opening it or by creating a new issue in this repository
